source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby '2.4.2'

gem 'rails', '~> 5.2'
gem 'sqlite3'
gem 'puma', '~> 3.7'
gem 'active_model_serializers', '~> 0.10.7'
gem 'jbuilder', '~> 2.7'
gem 'foreman', '~> 0.84.0'
gem 'rack-cors', '~> 1.0', '>= 1.0.2'
gem 'rack-attack', '~> 5.2'
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'knock', '~> 2.1', '>= 2.1.1'
gem 'jwt', '~> 1.5', '>= 1.5.6'
gem 'mini_magick', '~> 4.8'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'paperclip', '~> 6.0'
gem 'aws-sdk', '~> 3.0', '>= 3.0.1'

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'faker'

end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
